routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('suppliers', \App\Http\Controllers\SuppliersController::class);
Route::resource('stockdata1s', \App\Http\Controllers\Stockdata1sController::class);

app/Models/Stockdata1.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Stockdata1 extends Model
{
    use HasFactory;
}

app/Http/Controllers/Stockdata1sController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;

use App\Models\Stockdata1;
use App\Http\Requests\Stockdata1Request;

class Stockdata1sController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function index()
    {
        $stockdata1s= Stockdata1::all();
        return view('stockdata1s.index', ['stockdata1s'=>$stockdata1s]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function create()
    {
        return view('stockdata1s.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Stockdata1Request  $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Stockdata1Request $request)
    {
        $stockdata1 = new Stockdata1;
		$stockdata1->bahan = $request->input('bahan');
		$stockdata1->jumlah = $request->input('jumlah');
		$stockdata1->updateterakhir = $request->input('updateterakhir');
		$stockdata1->status = $request->input('status');
        $stockdata1->save();

        return to_route('stockdata1s.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\View
     */
    public function show($id)
    {
        $stockdata1 = Stockdata1::findOrFail($id);
        return view('stockdata1s.show',['stockdata1'=>$stockdata1]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\View
     */
    public function edit($id)
    {
        $stockdata1 = Stockdata1::findOrFail($id);
        return view('stockdata1s.edit',['stockdata1'=>$stockdata1]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Stockdata1Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Stockdata1Request $request, $id)
    {
        $stockdata1 = Stockdata1::findOrFail($id);
		$stockdata1->bahan = $request->input('bahan');
		$stockdata1->jumlah = $request->input('jumlah');
		$stockdata1->updateterakhir = $request->input('updateterakhir');
		$stockdata1->status = $request->input('status');
        $stockdata1->save();

        return to_route('stockdata1s.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $stockdata1 = Stockdata1::findOrFail($id);
        $stockdata1->delete();

        return to_route('stockdata1s.index');
    }
}

resources/views/stockdata1s/create.blade.php
@extends('default')

@section('content')
<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Tambah Data</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    </head>
    <body>
        <div class="container mt-5 mb-5">
            <div class="row">
                <div class="col-md-12">
                    <div class="card border-0 shadow rounded">
                        <div class="card-body">
                            <form action="{{ route('stockdata1s.store')}}" method="post" enctype="multipart/form-data">
	@if($errors->any())
		<div class="alert alert-danger">
			@foreach ($errors->all() as $error)
				{{ $error }} <br>
			@endforeach
		</div>
	@endif

	{!! Form::open(['route' => 'stockdata1s.store']) !!}

		<div class="mb-3">
			{{ Form::label('bahan', 'Bahan', ['class'=>'form-label']) }}
			{{ Form::text('bahan', null, array('class' => 'form-control')) }}
		</div>
		<div class="mb-3">
			{{ Form::label('jumlah', 'Jumlah', ['class'=>'form-label']) }}
			{{ Form::text('jumlah', null, array('class' => 'form-control')) }}
		</div>
		<div class="mb-3">
			{{ Form::label('updateterakhir', 'Update Terakhir', ['class'=>'form-label']) }}
			{{ Form::text('updateterakhir', null, array('class' => 'form-control')) }}
		</div>
		<div class="mb-3">
			{{ Form::label('status', 'Status', ['class'=>'form-label']) }}
			{{ Form::text('status', null, array('class' => 'form-control')) }}
		</div>


		{{ Form::submit('Create', array('class' => 'btn btn-primary')) }}

	{{ Form::close() }}
						</div>
                    </div>
                </div>
            </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script src="https://cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>
        <script>        
            CKEDITOR.replace('description')
        </script>
    </body>
    </html>

@stop

resources/views/stockdata1s/edit.blade.php
@extends('default')

@section('content')

	@if($errors->any())
		<div class="alert alert-danger">
			@foreach ($errors->all() as $error)
				{{ $error }} <br>
			@endforeach
		</div>
	@endif

	{{ Form::model($stockdata1, array('route' => array('stockdata1s.update', $stockdata1->id), 'method' => 'PUT')) }}

		<div class="mb-3">
			{{ Form::label('bahan', 'Bahan', ['class'=>'form-label']) }}
			{{ Form::text('bahan', null, array('class' => 'form-control')) }}
		</div>
		<div class="mb-3">
			{{ Form::label('jumlah', 'Jumlah', ['class'=>'form-label']) }}
			{{ Form::text('jumlah', null, array('class' => 'form-control')) }}
		</div>
		<div class="mb-3">
			{{ Form::label('updateterakhir', 'Updateterakhir', ['class'=>'form-label']) }}
			{{ Form::text('updateterakhir', null, array('class' => 'form-control')) }}
		</div>
		<div class="mb-3">
			{{ Form::label('status', 'Status', ['class'=>'form-label']) }}
			{{ Form::text('status', null, array('class' => 'form-control')) }}
		</div>

		{{ Form::submit('Edit', array('class' => 'btn btn-primary')) }}

	{{ Form::close() }}
@stop

resources/views/stockdata1s/index.blade.php
@extends('default')

@section('content')
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stock Data</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
</head>
<body>
<div class="container mt-5">
        <div class="row">   
            <div class="col-md-12">
                <div class="card border-0 shadow rounded">
                    <div class="card-body"> <center>
                        <a href="{{ route('stockdata1s.create')}}" class="btn btn-md btn-success mb-3">
                            TAMBAH DATA STOCK
                        </a> </center>
	<div class="d-flex justify-content-end mb-3"><a href="{{ route('stockdata1s.create') }}" class="btn btn-info">Create</a></div>

	<table class="table table-bordered">
		<thead>
			<tr>
				<th>id</th>
				<th>Nama Bahan</th>
				<th>Jumlah</th>
				<th>Update Terakhir</th>
				<th>Status</th>

				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			@foreach($stockdata1s as $stockdata1)

				<tr>
					<td>{{ $stockdata1->id }}</td>
					<td>{{ $stockdata1->bahan }}</td>
					<td>{{ $stockdata1->jumlah }}</td>
					<td>{{ $stockdata1->updateterakhir }}</td>
					<td>{{ $stockdata1->status }}</td>

					<td>
						<div class="d-flex gap-2">
                            <a href="{{ route('stockdata1s.show', [$stockdata1->id]) }}" class="btn btn-info">Show</a>
                            <a href="{{ route('stockdata1s.edit', [$stockdata1->id]) }}" class="btn btn-primary">Edit</a>
                            {!! Form::open(['method' => 'DELETE','route' => ['stockdata1s.destroy', $stockdata1->id]]) !!}
                                {!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
                            {!! Form::close() !!}
                        </div>
					</td>
				</tr>

			@endforeach
		</tbody>
	</table>
					</div>
                </div>
            </div>
        </div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script>        
        //message with toastr
        @if (session()->has('success'))
            toastr.success('{{ session('success') }}', 'BERHASIL!');
        @elseif (session()->has('error'))
            toastr.error('{{ session('error') }}', 'GAGAL!');
        @endif
    </script>
</body>
</html>
@stop

resources/views/stockdata1s/show.blade.php
@extends('default')

@section('content')

	{{ $stockdata1->id }}

@stop